## Classification model configuration

data:
  input_dir: data/mvp/ProtLM_embeddings_with_labels/

split:
  val_organisms: [WCS417, Putida, DdiaME23, Burk376]
  test_organisms: [Koxy, psRCH2, Korea, BFirm]
  train_organisms:
    - ANA3
    - Cup4G11
    - Dda3937
    - Ddia6719
    - Dyella79
    - HerbieS
    - Keio
    - MR1
    - PV4
    - Pedo557
    - SB2B
    - Smeli
    - acidovorax_3H11
    - azobra
    - pseudo13_GW456_L13
    - pseudo1_N1B4
    - pseudo3_N2E3
    - pseudo5_N2C3_1
    - pseudo6_N2E2